import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Nav from "@/components/nav.jsx";
import Footer from "@/components/footer.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="sticky top-0 z-50">
          <Nav />
        </div>

        {children}
        <Footer />
      </body>
    </html>
  );
}
